spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://qmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://qmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://qmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://qmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://qmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://qmall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/qmall-admin/$\{segment}

        - id: qmall_host_route
          uri: lb://qmall-product
          predicates:
            - Host=qmall.com,item.qmall.com

        - id: qmall_search_route
          uri: lb://qmall-search
          predicates:
            - Host=search.qmall.com

        - id: qmall_auth_route
          uri: lb://qmall-auth-server
          predicates:
            - Host=auth.qmall.com

        - id: qmall_cart_route
          uri: lb://qmall-cart
          predicates:
            - Host=cart.qmall.com

        - id: qmall_order_route
          uri: lb://qmall-order
          predicates:
            - Host=order.qmall.com

        - id: qmall_member_route
          uri: lb://qmall-member
          predicates:
            - Host=member.qmall.com

        - id: qmall_seckill_route
          uri: lb://qmall-seckill
          predicates:
            - Host=seckill.qmall.com
