spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tK14G174nbYRjpvXnE1
      secret-key: rgfuEdkSzl4FReTpRkwoghg9GeM4pv
      oss:
        endpoint: oss-ap-southeast-2.aliyuncs.com
        bucket: gulimall-hostgov
  application:
    name: qmall-third-party
server:
  port: 30000


